urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MetaMagazine.views.home', name='home'),
    # url(r'^MetaMagazine/', include('MetaMagazine.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # Django built-in users system
    url(r'^login', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^logout', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}),
    
    # Static files:
    url(r'^css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'static/css'}),
    url(r'^js/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'static/js'}),    
    url(r'^img/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'static/img'}),        
    
    url(r'^magazines/add', 'metaapp.views.add_channel'),
    url(r'^magazines/(?P<user>.*)$', 'metaapp.views.show_magazine'),
    url(r'^magazines$', 'metaapp.views.show_magazines'),

    url(r'^channels$', 'metaapp.views.show_channels'),
    
    url(r'^news/(?P<newsid>.*)$', 'metaapp.views.show_news'),        
    url(r'^api/news/(?P<newsid>.*)$', 'metaapp.views.show_news_api'),        
    
    url(r'^changetitle$','metaapp.views.changetitle'),
    
    url(r'^update/(?P<idchannel>.*)$', 'metaapp.views.update_channel'),    
    url(r'^delete/(?P<idchannel>.*)$', 'metaapp.views.delete_channel'),    
    url(r'^conf$', 'metaapp.views.conf'),    

    url(r'^$', 'metaapp.views.root'),
    
)

metaapp/models.py
from django.db import models

# Create your models here.
class Magazine(models.Model):
   user = models.TextField(primary_key=True)
   title = models.TextField()
   
class Channel(models.Model):
   href = models.TextField()
   last = models.DateField()
   limit = models.IntegerField()
   magazine = models.ForeignKey(Magazine)
   
class News(models.Model):
   text = models.TextField()
   href = models.TextField()
   channel = models.ForeignKey(Channel)

class Url(models.Model):
   href = models.TextField()
   extract = models.TextField()
   video = models.TextField()
   news = models.ForeignKey(News)
    
class Img(models.Model):
   src = models.TextField()
   url = models.ForeignKey(Url)

templates/apinews.html
<p>
	Ver en <a href="/news/{{new.id}}">MetaMagazine</a>
	<a href="{{new.href}}">Sitio Original</a>
<p>
<ol>
	{% for url in new.url_set.all %}
		<li>
			<p><a href="{{url.href}}">{{url.extract|safe}}</a></p>
			{% if url.video %}<p><b>Video: </b>{{url.video|safe}}</p>{% endif %}
			{% for img in url.img_set.all %}
				<img src="{{img.src}}" alt=""/>
			{% endfor %}
		</li>
	{% endfor %}
</ol>

templates/base.html
{% load url from future %}

<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="author" content="Julio Iván Alegre Torrejón">
    <link rel="stylesheet" href="/css/style.css" />
	<script src="/js/magazine.js" type="text/javascript" charset="utf-8"></script>
    <title>{% block title %}MetaMagazine{% endblock %}</title>
</head>

<body>
	<table class="topbar">
		<tr>
			<td>
				{% block login %}
				{% endblock %}
			</td>
			<td class="menu">
				{% if user.is_authenticated %}
					<a href="/magazines/{{user}}">Mi revista</a>  <a href="/conf">Mi cuenta</a>
				{% endif %}
			</td>
		</tr>
	</table>
	<hr />
	<a href="/"><img src="/img/logo.png" alt="" /></a>
   	{% block content %}{% endblock %}
	<div class="footer">
		Created by <a href="http://yonkiblog.com">J. Iván Alegre Torrejón</a>
	</div>
</body>
</html>

templates/changetitle.html
{% extends "base.html" %}

{% block login %}
{{login|safe}}
{% endblock %}

{% block content %}
	{{success|safe}}
	<form action="/changetitle" method="post">
	{% csrf_token %}
		<p><label>Nuevo título: <input type="text" name="title" /></label>
		<input type="submit" value="Cambiar" /></p>
	</form>
{% endblock %}

templates/channels.html
{% extends "base.html" %}

{% block login %}
{{login|safe}}
{% endblock %}

{% block content %}
	<h1>Lista de canales</h1>
	<ul>
		{% for channel in channels %}
		<li>
			<a href="{{channel.href}}">{{channel.href}}</a> actualizado por última vez {{channel.last}}
			perteneciente a la revista de {{channel.magazine.user}}
		</li>
		{% endfor %}
	</ul>
{% endblock %}

templates/conf.html
{% extends "base.html" %}

{% block login %}
{{login|safe}}
{% endblock %}

{% block content %}
	{{success|safe}}
	<form action="/conf" method="post">
	{% csrf_token %}
	<table>
		<tr><td><label>Nuevo nombre: </td><td><input type="text" name="name" /></label></td></tr>
		<tr><td><label>Contraseña: </td><td><input type="password" name="pwd" /></label></td></tr>
		<tr><td><label>Contraseña (de nuevo): </td><td><input type="password" name="pwd2" /></label></td></tr>
		<tr><td><input type="submit" value="Cambiar datos" /></td></tr>
	</table>
	</form>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load url from future %}

{% block title %}
Login
{% endblock %}

{% block content %}

	{% if form.errors %}
		<p>Your username and password didn't match. Please try again.</p>
	{% endif %}

	<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
	{% csrf_token %}
	<table>
	<tr>
	    <td>{{ form.username.label_tag }}</td>
	    <td>{{ form.username }}</td>
	</tr>
	<tr>
	    <td>{{ form.password.label_tag }}</td>
	    <td>{{ form.password }}</td>
	</tr>
	</table>

	<input type="submit" value="login" />
	<input type="hidden" name="next" value="/" />
	</form>

{% endblock %}

templates/logout.html
{% extends "base.html" %}
{% load url from future %}

{% block title %}
Logout
{% endblock %}

{% block content %}

	<p>You have been logged out</p>
	<p><a href="/login">Log in again</a> or <a href="/">return to home</a></p>

{% endblock %}

templates/magazine.html
{% extends "base.html" %}

{% block login %}
{{login|safe}}
{% endblock %}

{% block content %}
	<h1>{{title}}</h1>
	{% if own %}
		<a href="/changetitle">Cambiar título</a>
	{% endif %}
	{% if usuario %}
		<p>(by {{usuario}})</p><button onclick="showAll('new')">Mostrar todas las noticias</button>
	{% endif %}
	
	{% if own %}
		{{success|safe}}
		<form action="/magazines/add" method="post">
		{% csrf_token %}
			<p>Añadir canal: <label>Usuario: <input type="text" name="user" /></label>
			<label for="type">Selecciona el tipo de canal</label>
				<select id="type" name="type">
					<option selected label="twitter" value="twitter">Twitter</option>
					<option label="identica" value="identica">Identi.ca</option>
					<option label="youtube" value="youtube">Youtube</option>
				</select>
			<label>Nº de noticias a extraer (max 10)<input type="text" name="limit" /></label>
			<input type="submit" value="Añadir" /></p>
		</form>
	{% endif %}
	
	<ul>
		{% for channel in channels %}
		<li>
			<a href="{{channel.href}}">{{channel.href}}</a> {{channel.last}} {% if own %}<a href="/update/{{channel.id}}">Actualizar</a><a href="/delete/{{channel.id}}">  Eliminar</a>{% endif %}
			<ul>
				{% for new in channel.news_set.all reversed %}
				<li>
					<p>{{new.text}}</p>
					<button onclick="showNew({{new.id}})">Mostrar noticia</button>
					<div class="new" id="new{{new.id}}"></div>
				</li>
				{% endfor %}
			</ul>
		</li>
		{% endfor %}
	</ul>
{% endblock %}

templates/magazines.html
{% extends "base.html" %}

{% block login %}
{{login|safe}}
{% endblock %}

{% block content %}
	<h1>Lista de revistas disponibles</h1>
	<ul>
		{% for magazine in magazines %}
		<li>
			<a href="/magazines/{{magazine.user}}">{{magazine.title}}</a> de {{magazine.user}}
		</li>
		{% endfor %}
	</ul>
{% endblock %}

templates/news.html
{% extends "base.html" %}

{% block login %}
{{login|safe}}
{% endblock %}

{% block content %}
	<p>
		Ver en <a href="/news/{{new.id}}">MetaMagazine</a>
		<a href="{{new.href}}">Sitio Original</a>
	<p>
	<ol>
		{% for url in new.url_set.all %}
			<li>
				<p><a href="{{url.href}}">{{url.extract|safe}}</a></p>
				{% if url.video %}<p><b>Video: </b>{{url.video|safe}}</p>{% endif %}
				{% for img in url.img_set.all %}
					<img src="{{img.src}}" alt=""/>
				{% endfor %}
			</li>
		{% endfor %}
	</ol>
{% endblock %}

templates/root.html
{% extends "base.html" %}

{% block login %}
{{login|safe}}
{% endblock %}

{% block content %}
	<h1>Bienvenido a MetaMagazine</h1>
	<p>Metamagazine es un sitio web hecho en <a href="http://djangoproject.org">Django</a>. Está en en una frase de desarrollo muy poco avanzada, por lo que es muy posible que encuentres errores.</p>
	<p>El objetivo de MetaMagazine es reunir en un sólo sitio a la gente que sigues en twitter, identi.ca y youtube. Además, extrae información relevante de los sitios web que aparecen en tweets (tanto de twitter como de identica), de forma que no siempre tengas que visitar el sitio web enlazado en un tweet para saber que contiene.</p>
	<p>Ya sólo queda disfrutarlo. Para ello tienes varias opciones:
		<ol>
			<li>Ir a la revista de un usuario, debes ir a /magazines/&lt;user&gt;</li>
			<li>Ver las revistas disponibles <a href="/magazines">/magazines</a></li>
			<li>Ver una lista de canales activos <a href="/channels">/channels</a></li>
			<li>Ver una noticia en concreto /news/&lt;id&gt;</li>
			{% if user.username %}
			<li>Y por supuesto, ver <a href="/magazines/{{user}}">tu revista</a>, añadir canales y demás</li>
			{% endif %}
		</ol>
	</p>
	{% if usuario %}
		<p>Ahora te mostramos una noticia aleatoria, en concreto, la <a href="/magazines/{{usuario}}">revista de {{usuario}}</a></p>
	{% endif %}
	<h2>{{title}}</h2>
	{% if own %}
		<a href="/changetitle">Cambiar título</a>
	{% endif %}
	{% if usuario %}
		<p>(by {{usuario}})</p><button onclick="showAll('new')">Mostrar todas las noticias</button>
	{% endif %}

	{% if own %}
		{{success|safe}}
		<form action="/magazines/add" method="post">
		{% csrf_token %}
			<p>Añadir canal: <label>Usuario: <input type="text" name="user" /></label>
			<label for="type">Selecciona el tipo de canal</label>
				<select id="type" name="type">
					<option selected label="twitter" value="twitter">Twitter</option>
					<option label="identica" value="identica">Identi.ca</option>
					<option label="youtube" value="youtube">Youtube</option>
				</select>
			<label>Nº de noticias a extraer (max 10)<input type="text" name="limit" /></label>
			<input type="submit" value="Añadir" /></p>
		</form>
	{% endif %}
	
	<ul>
		{% for channel in channels %}
		<li>
			<a href="{{channel.href}}">{{channel.href}}</a> {{channel.last}} {% if own %}<a href="/update/{{channel.id}}">Actualizar</a><a href="/delete/{{channel.id}}">  Eliminar</a>{% endif %}
			<ul>
				{% for new in channel.news_set.all reversed %}
				<li>
					<p>{{new.text}}</p>
					<button onclick="showNew({{new.id}})">Mostrar noticia</button>
					<div class="new" id="new{{new.id}}"></div>
				</li>
				{% endfor %}
			</ul>
		</li>
		{% endfor %}
	</ul>
{% endblock %}

templates/user.html
{% extends "base.html" %}

{% block login %}
{{login|safe}}
{% endblock %}

{% block content %}
	{{success|safe}}
{% endblock %}